# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10, verbose_name='source')),
                ('scraped_at', models.DateTimeField(verbose_name='scraped at')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('country', models.CharField(max_length=24, verbose_name='country')),
                ('ip_addr', models.CharField(max_length=16, verbose_name='ip address')),
                ('port', models.IntegerField(verbose_name='port')),
                ('proto', models.CharField(max_length=5, verbose_name='protocol')),
                ('anonimity', models.CharField(max_length=8, verbose_name='anonimity')),
                ('speed_qual', models.IntegerField(verbose_name='speed quality')),
                ('connect_qual', models.IntegerField(verbose_name='connect quality')),
            ],
            options={
                'verbose_name_plural': 'proxies',
                'verbose_name': 'proxy',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together=set([('ip_addr', 'port', 'source')]),
        ),
    ]
